In [1]:
import pandas as pd

In [2]:
students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Arpit", "Rahul", "Subdil"]
})

students

   ID    Name
0   1   Arpit
1   2   Rahul
2   3  Subdil

In [3]:
marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "marks": ["90", "75", "87"]
})

marks

   ID marks
0   1    90
1   2    75
2   3    87

In [4]:
pd.merge(students, marks, on="ID")

   ID    Name marks
0   1   Arpit    90
1   2   Rahul    75
2   3  Subdil    87

In [5]:
pd.merge(students, marks, on="ID", how="inner")

   ID    Name marks
0   1   Arpit    90
1   2   Rahul    75
2   3  Subdil    87

In [6]:
pd.merge(students, marks, on="ID", how="right")

   ID    Name marks
0   1   Arpit    90
1   2   Rahul    75
2   3  Subdil    87

In [7]:
pd.merge(students, marks, on="ID", how="outer")

   ID    Name marks
0   1   Arpit    90
1   2   Rahul    75
2   3  Subdil    87

In [8]:
df1 = pd.DataFrame({
    "Name": ["Arpit", "Rahul"]
})

df2 = pd.DataFrame({
    "Name": ["Priya", "Aman"]
})

pd.concat([df1, df2])

    Name
0  Arpit
1  Rahul
0  Priya
1   Aman

In [9]:
pd.concat([df1, df2], axis=1)

    Name   Name
0  Arpit  Priya
1  Rahul   Aman

In [11]:
players = pd.DataFrame({
    "PlayerID": [1, 2, 3, 4],
    "Name": ["Mbappe", "Messi", "Ronaldo", "Haaland"],
    "Club": ["Real Madrid", "Inter Miami", "Al Nassr", "Man City"]
})

In [12]:
stats = pd.DataFrame({
    "PlayerID": [1, 2, 3, 5],
    "Goals": [30, 25, 20, 35],
    "Assists": [10, 15, 8, 5]
})

In [13]:
print(pd.merge(players, stats, on="PlayerID", how="inner"))

   PlayerID     Name         Club  Goals  Assists
0         1   Mbappe  Real Madrid     30       10
1         2    Messi  Inter Miami     25       15
2         3  Ronaldo     Al Nassr     20        8

In [14]:
print(pd.merge(players, stats, on="PlayerID", how="left"))

   PlayerID     Name         Club  Goals  Assists
0         1   Mbappe  Real Madrid   30.0     10.0
1         2    Messi  Inter Miami   25.0     15.0
2         3  Ronaldo     Al Nassr   20.0      8.0
3         4  Haaland     Man City    NaN      NaN

In [15]:
print(pd.merge(players, stats, on="PlayerID", how="outer"))

   PlayerID     Name         Club  Goals  Assists
0         1   Mbappe  Real Madrid   30.0     10.0
1         2    Messi  Inter Miami   25.0     15.0
2         3  Ronaldo     Al Nassr   20.0      8.0
3         4  Haaland     Man City    NaN      NaN
4         5      NaN          NaN   35.0      5.0

In [17]:
extra = pd.DataFrame({
    "PlayerID": [6],
    "Name": ["Vinicius"],
    "Club": ["Real Madrid"]
})
print(pd.concat([players, extra], ignore_index=True))

   PlayerID      Name         Club
0         1    Mbappe  Real Madrid
1         2     Messi  Inter Miami
2         3   Ronaldo     Al Nassr
3         4   Haaland     Man City
4         6  Vinicius  Real Madrid